spring:
  config:
    import: optional:file:.env[.properties] # @value anotaion을 사용하기 위해 env 파일 읽기위함

  application:
    name: backend           # 애플리케이션 이름 (로그, 모니터링 식별용)

  datasource:
    url: ${DB_URL}        # Render PostgreSQL 접속 URL (환경변수)
    username: ${DB_USERNAME} # DB 계정명 (환경변수)
    password: ${DB_PASSWORD} # DB 비밀번호 (환경변수)
    driver-class-name: org.postgresql.Driver # PostgreSQL JDBC 드라이버

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # DB camelCase 자동 매핑
    # 쿼리 그대로 콘솔에 출력
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    # Mapper 패키지 전체 DEBUG
    com.wms.backend.mapper: debug
    # MyBatis 내부 SQL 로깅
    org.mybatis: debug


